# Generated by Django 5.1.2 on 2024-11-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionapi',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
